services:
  portfolio-cms:
    container_name: portfolio-cms
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: portfolio-cmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      HOST: '0.0.0.0'
      PORT: 1337
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - portfolio-cms
    depends_on:
      - portfolio-cmsDB

  portfolio-cmsDB:
    container_name: portfolio-cmsDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - portfolio-cms-data:/var/lib/mysql
    networks:
      - portfolio-cms

volumes:
  portfolio-cms-data:


networks:
  portfolio-cms:
    name: Portfolio-cms
    driver: bridge
